### ISSUE TITLE
没有一级标题时，二级标题编号无法正常编号

### ISSUE THREAD

**Issue by Shawn-Guo-CN** [yfzhao20/Typora-markdown#1]
下面这段源代码，编译出的结果，所有二级标题的编号都是1。
```
## Task Description
- Good Points:
   1. Your task description is good.
- Bad points:
   1. You may need explain why the problem is modelled as a (binary)/(trinary) classification problem.
   2. But you could have done a better job at motivating the project for this particular dataset.

## Motivation of the Project/Dataset

- Good Points:
  1. You motivate the task, sentiment analysis, quite well.
  2. You mention the significance of this task.

- Bad Points:
  1. You may want to motivate the task, sentiment analysis, itself.
  2. You barely explain why to analyse this dataset in the first place.
```

如果插入一级标题之后，就能正确编号。

**Comment by yfzhao20** [comment]
确实，这是一个老问题。而且如果直接开始使用三级标题，会发现第一位数字变成了0。

**目前暂时没有找到更好的解决方法，可以添加一个空的一级标题试试。**

会在进一步学习css之后试着改进它。

**Comment by yfzhao20** [comment]
但是会引入新的问题：如果一级标题和二级标题都没有，那么还是会乱😂

**Comment by deelsilcon** [comment]
> 但是会引入新的问题：如果一级标题和二级标题都没有，那么还是会乱😂

重置计数器的时候应该把比它级别小的标题的计数器都重置一次吧，这样逻辑好像更完整一些，当时没有考虑到。
```css
h1 {
    counter-reset: h2 0 h3 0 h4 0 h5 0 h6 0
}

h2 {
    counter-reset: h3 0 h4 0 h5 0 h6 0
}

h3 {
    counter-reset: h4 0 h5 0 h6 0
}

h4 {
    counter-reset: h5 0 h6 0
}

h5 {
    counter-reset: h6 0
}
```
不知道你描述的是不是这个问题。
